config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'reset_passwords/new'
  resources :sessions, oonly: %i[new create destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
  resources :users, only: %i[new create] do
    member do
      get :activate
    end
  end
  resources :reset_passwords, only: %i[new create update edit]
  get '/sign_up', to: 'users#new', as: :sign_up
  get 'users/create'
  get '/secret', to: 'pages#index', as: :secret
  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = 'You have to authenticated to access the secret'
    redirect_to log_in_path
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  # before_action :require_login, only: %i[secret]
  def index; end

  def secret; end
end

app/controllers/reset_passwords_controller.rb
# frozen_string_literal: true

class ResetPasswordsController < ApplicationController
  skip_before_action :require_login
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    @user.deliver_reset_password_instructions!
    if @user
      flash[:success] = 'instruction have been sent to your email'
      redirect_to log_in_path
    end
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated && return if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      flash[:success] = 'Password was successfully updated.'
      redirect_to log_in_path
    else
      render 'edit'
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new; end

  def create
    if login(params[:email], params[:password], params[:remember_me])
      flash[:success] = 'welcome back'
      redirect_back_or_to root_path
    else
      flash.now[:warning] = 'email or password is incorrect!'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'good bye!'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :require_login
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome!'
      redirect_to log_in_path
    else
      render 'new'
    end
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      flash[:success] = 'User was successfully activated.'
      redirect_to secret_path
    else
      flash[:warning] = 'Cannot activate this user.'
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/reset_passwords_helper.rb
# frozen_string_literal: true

module ResetPasswordsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SorceryAuth2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-inverse">
     <div class="container">
       <div class="navbar-header">
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
       </div>
       <div id="navbar">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <p><%= link_to 'Secret Page', secret_path %></p>
          <% else %>
            <button class="btn"><%= link_to 'Sign Up', sign_up_path %></button>
            <button><%= link_to 'Log In', log_in_path %></button>
          <% end %>
        </ul>
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li><span><%= current_user.email.split('@').first %></span></li>
            <button><%= link_to 'Log Out', log_out_path, method: :delete %></button>
          </ul>
          <% end %>
       </div>
     </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome</h1>
<p>please signup or login to access the "secret"!</p>

app/views/pages/secret.html.erb
<h1>SECRET PAGE</h1>
<h4>You have discovered my secret!</h4>
<p>this page is restricted area!</p>

app/views/reset_passwords/edit.html.erb
<h1>Choose a new password</h1>

    <%= form_for @user, url: reset_password_path(@token), method: :patch do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
      </div>

        <%= f.submit 'Set password', class: 'btn btn-primary btn-lg' %>
    <% end %>

app/views/reset_passwords/new.html.erb
<h1>Reset Password</h1>

<%= form_tag reset_passwords_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email, nil, class: 'form-control', required: true %>
  </div>

  <%= submit_tag "send reset password instruction", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Registration</h1>
<%= form_for @user do |f| %>
<%= render 'shared/error_messages', object: @user %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>

    <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>